// VERIFIER
export const VERIFIER_LOGIN = 'VERIFIER_LOGIN';
export const VERIFIER_SIGNUP = 'VERIFIER_SIGNUP';
export const VERIFIER_LOGOUT = 'VERIFIER_LOGOUT';
export const GET_ALL_VERIFICATIONS_DETAILS = 'GET_ALL_VERIFICATIONS_DETAILS';
export const SET_VERIFIER_PROFILE_DETAILS = 'SET_VERIFIER_PROFILE_DETAILS';

//EMPLOYER
export const EMPLOYER_LOGIN = 'EMPLOYER_LOGIN';
export const EMPLOYER_LOGOUT = 'EMPLOYER_LOGOUT';
export const GET_ALL_EMPLOYER_VERIFICATION = 'GET_ALL_EMPLOYER_VERIFICATION';
