// VERIFIER
export const VERIFIER_LOGIN = 'VERIFIER_LOGIN';
export const VERIFIER_SIGNUP = 'VERIFIER_SIGNUP';
export const VERIFIER_LOGOUT = 'VERIFIER_LOGOUT';
export const GET_ALL_VERIFICATIONS_DETAILS = 'GET_ALL_VERIFICATIONS_DETAILS';
export const SET_VERIFIER_PROFILE_DETAILS = 'SET_VERIFIER_PROFILE_DETAILS';

//EMPLOYER
export const EMPLOYER_LOGIN = 'EMPLOYER_LOGIN';
export const EMPLOYER_LOGOUT = 'EMPLOYER_LOGOUT';
export const GET_ALL_EMPLOYER_VERIFICATION = 'GET_ALL_EMPLOYER_VERIFICATION';
export const SET_EMPLOYER_PROFILE_DETAILS = 'SET_EMPLOYER_PROFILE_DETAILS';

//ADMIN
export const ADMIN_LOGIN = 'ADMIN_LOGIN';
export const ADMIN_LOGOUT = 'ADMIN_LOGOUT';
export const GET_ALL_EMPLOYERS = 'GET_ALL_EMPLOYERS';
